"""empty message

Revision ID: a8508a7b2c93
Revises: aaa9f06390eb
Create Date: 2026-03-05 13:48:58.552705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8508a7b2c93'
down_revision: Union[str, Sequence[str], None] = 'aaa9f06390eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_groups', sa.Column('type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_groups', 'type')
    # ### end Alembic commands ###
